hyperskill_project:
  id: 180
  ide_files: https://cogniterra.org/media/attachments/lesson/25525/additional_files.json
  is_template_based: false
  use_ide: true
update_date: "Sat, 15 Feb 2025 17:41:01 UTC"
stages:
  - id: 917
    step: 13088
    is_completed: true
  - id: 918
    step: 13089
    is_completed: true
  - id: 919
    step: 13090
    is_completed: true
  - id: 920
    step: 13091
    is_completed: false
  - id: 921
    step: 13092
    is_completed: false
topics:
  0:
    - title: Modulo division
      theory_id: 10586
    - title: Computer algorithms
      theory_id: 16547
    - title: Comparing algorithms with big O
      theory_id: 35900
    - title: "Big O: how to count it"
      theory_id: 35901
    - title: "Best, average, and worst cases"
      theory_id: 40157
    - title: Complexity cases and how to use them
      theory_id: 20084
    - title: Data structures
      theory_id: 40371
    - title: Abstract and concrete data structures
      theory_id: 16927
    - title: "Write, compile, and run"
      theory_id: 3739
    - title: "Basic terms: JVM, JRE, JDK"
      theory_id: 3499
    - title: Operating systems
      theory_id: 9704
    - title: Command line overview
      theory_id: 8977
    - title: Parameters and options
      theory_id: 9746
    - title: Running programs on your computer
      theory_id: 3746
    - title: Units of information
      theory_id: 6865
    - title: IDE
      theory_id: 10996
    - title: World Wide Web
      theory_id: 6633
    - title: "HTTP: HyperText Transfer Protocol"
      theory_id: 6569
    - title: Spring and Spring Boot frameworks
      theory_id: 7944
    - title: Getting started with Spring Boot
      theory_id: 6336
    - title: Immutability
      theory_id: 7929
    - title: Pseudocode
      theory_id: 15090
    - title: Pseudocode basics
      theory_id: 19510
    - title: Fixed-size array
      theory_id: 20078
    - title: Dynamic array
      theory_id: 5357
    - title: Basic project structure
      theory_id: 6339
    - title: IoC Container
      theory_id: 16851
    - title: Spring beans
      theory_id: 14641
    - title: Spring components
      theory_id: 14652
    - title: '@Bean vs @Component'
      theory_id: 14771
    - title: ApplicationContext
      theory_id: 22062
    - title: Scopes of beans
      theory_id: 19487
    - title: Bean lifecycle
      theory_id: 19550
    - title: Spring Stereotypes
      theory_id: 38935
    - title: HTTP URL
      theory_id: 6740
    - title: Introduction to Spring Web MVC
      theory_id: 13611
    - title: HTTP messages
      theory_id: 6752
    - title: REST
      theory_id: 7834
    - title: Postman
      theory_id: 8512
    - title: Introduction to Spring Data
      theory_id: 16299
    - title: "CRUD Repositories: Create and Read"
      theory_id: 38290
    - title: "CRUD Repositories: Update and Delete"
      theory_id: 38918
    - title: Application layers
      theory_id: 13971
    - title: Data Transfer Object in Spring
      theory_id: 25613
    - title: Relations and conditions in pseudocode
      theory_id: 39411
    - title: Complex constructions in pseudocode
      theory_id: 20922
    - title: Introduction to Java
      theory_id: 38627
    - title: "Basic literals: numbers, strings and characters"
      theory_id: 3522
    - title: Writing first program
      theory_id: 3521
    - title: Printing data
      theory_id: 3749
    - title: Types and variables
      theory_id: 3518
    - title: Comments
      theory_id: 3520
    - title: Reading user's input with Scanner
      theory_id: 9055
    - title: Coding style conventions
      theory_id: 12411
    - title: Naming variables
      theory_id: 3513
    - title: Arithmetic operations
      theory_id: 3519
    - title: Integer types and operations
      theory_id: 3565
    - title: Increment and decrement
      theory_id: 5008
    - title: Data types and their sizes
      theory_id: 3532
    - title: Type casting
      theory_id: 3510
    - title: Calling methods
      theory_id: 10973
    - title: Floating-point types
      theory_id: 3517
    - title: Boolean type and operations. True and false
      theory_id: 3516
    - title: Comparing values. Relational operators
      theory_id: 3512
    - title: Conditional statement
      theory_id: 3503
    - title: One-line condition with ternary operator
      theory_id: 3506
    - title: For loop
      theory_id: 3505
    - title: While and do-while loops
      theory_id: 3498
    - title: Break and continue. Branching
      theory_id: 3507
    - title: Declaring methods
      theory_id: 10982
    - title: Method "main"
      theory_id: 3489
    - title: "Multiple conditions: switch"
      theory_id: 3504
    - title: Functional decomposition
      theory_id: 10570
    - title: Overloading
      theory_id: 3525
    - title: Primitive and reference types
      theory_id: 5035
    - title: Array
      theory_id: 3511
    - title: Arrays as parameters
      theory_id: 3594
    - title: Iterating over arrays
      theory_id: 3602
    - title: Characters
      theory_id: 3514
    - title: String
      theory_id: 3523
    - title: Constants. Final variables
      theory_id: 7427
    - title: Errors in programs
      theory_id: 3536
    - title: First glance at exceptions
      theory_id: 3497
    - title: NullPointerException
      theory_id: 1945
    - title: What is object-oriented programming
      theory_id: 3614
    - title: Hierarchy of exceptions
      theory_id: 3570
    - title: Exception handling
      theory_id: 3552
    - title: Build tools
      theory_id: 4284
    - title: JAR files
      theory_id: 4311
    - title: "Gradle: overview"
      theory_id: 5075
    - title: Basic project with Gradle
      theory_id: 5077
    - title: Building apps using Gradle
      theory_id: 7917
    - title: Gradle build configuration
      theory_id: 35988
    - title: "Dependency management: repositories"
      theory_id: 37189
    - title: External resources
      theory_id: 6216
    - title: Web development
      theory_id: 13931
    - title: Libraries
      theory_id: 8504
    - title: Frameworks
      theory_id: 6701
    - title: Concept of design patterns
      theory_id: 3611
    - title: What are bugs
      theory_id: 5504
    - title: Functional testing
      theory_id: 13438
    - title: Unit testing
      theory_id: 7545
    - title: Dependency injection
      theory_id: 20580
    - title: Introduction to software architecture
      theory_id: 15368
    - title: Class Diagrams
      theory_id: 15588
    - title: Interfaces
      theory_id: 9640
    - title: YAML
      theory_id: 12722
    - title: Code organization. Design principles
      theory_id: 8956
    - title: Coupling and cohesion
      theory_id: 21478
    - title: "Synchronous, asynchronous, parallel"
      theory_id: 9332
    - title: Processes and threads
      theory_id: 9420
    - title: What are databases
      theory_id: 8497
    - title: HTML Basics
      theory_id: 47192
    - title: Tags and Attributes
      theory_id: 7536
    - title: HTML page structure
      theory_id: 6491
    - title: Relational Data Model
      theory_id: 13785
    - title: Debugging overview
      theory_id: 14368
    - title: "Hashing: overview"
      theory_id: 9831
    - title: JSON
      theory_id: 6854
    - title: XML
      theory_id: 6901
    - title: Data and object mapping
      theory_id: 8262
    - title: Object-Relational Mapping (ORM)
      theory_id: 8312
    - title: Introduction to JPA
      theory_id: 17125
    - title: Hash function
      theory_id: 30143
    - title: Hash table
      theory_id: 13054
    - title: Introduction to API
      theory_id: 17007
    - title: IntelliJ IDEA
      theory_id: 37202
    - title: Run and debug with IntelliJ IDEA
      theory_id: 37206
    - title: Debugging simple constructs
      theory_id: 16479
    - title: IntelliJ IDEA run configurations
      theory_id: 10630
    - title: Getting data from REST
      theory_id: 13287
    - title: Posting and deleting data via REST
      theory_id: 13292
    - title: Handling requests with bodies
      theory_id: 13334
    - title: Customizing REST responses
      theory_id: 33247
    - title: Introduction to generic programming
      theory_id: 3492
    - title: Generics and Object
      theory_id: 3493
    - title: Lambda expressions
      theory_id: 11635
    - title: What are collections
      theory_id: 3770
    - title: The Collections framework overview
      theory_id: 3624
    - title: ArrayList
      theory_id: 3567
    - title: The List interface
      theory_id: 3581
    - title: The Set interface
      theory_id: 3575
    - title: Creational design patterns
      theory_id: 16251
    - title: Factory Method and Prototype
      theory_id: 16430
    - title: Threads as objects
      theory_id: 4875
    - title: Custom threads
      theory_id: 4876
    - title: Thread management
      theory_id: 3619
    - title: Exceptions in threads
      theory_id: 4882
    - title: Shared data
      theory_id: 3610
    - title: Thread synchronization
      theory_id: 3557
    - title: Collections and thread-safety
      theory_id: 4984
    - title: MVC
      theory_id: 17197
    - title: Entities
      theory_id: 18135
    - title: The Map interface
      theory_id: 3558
    - title: Thread-safe maps
      theory_id: 17081
    - title: Defining classes
      theory_id: 3618
    - title: Grouping classes with packages
      theory_id: 3621
    - title: Instance methods
      theory_id: 3495
    - title: Initializing new instances. Constructor
      theory_id: 3535
    - title: Access modifiers
      theory_id: 3589
    - title: Getters and setters
      theory_id: 3599
    - title: Inheritance
      theory_id: 3583
    - title: Protected modifier
      theory_id: 6692
    - title: Referencing subclass objects
      theory_id: 3585
    - title: Multiple constructors
      theory_id: 3538
    - title: Keyword "super"
      theory_id: 3588
    - title: Object class
      theory_id: 3596
    - title: Objects and their properties
      theory_id: 4727
    - title: Static members
      theory_id: 3534
    - title: Adding annotations
      theory_id: 3622
    - title: Method overriding
      theory_id: 3572
    - title: Polymorphism
      theory_id: 3587
    - title: Declaring functionality with interfaces
      theory_id: 3615
    - title: Wrapping classes. Boxing
      theory_id: 3595
  1:
    - title: Exception handling in Spring Boot
      theory_id: 8780
    - title: Reflection basics
      theory_id: 3609
    - title: Introduction to logging
      theory_id: 5538
    - title: Debugging techniques
      theory_id: 13775
    - title: HashMap
      theory_id: 12379
    - title: hashCode() and equals() in Collections
      theory_id: 19587
    - title: Runtime type checking
      theory_id: 3571
    - title: hashCode() and equals()
      theory_id: 3586
  2:
    - title: CRUD repositories
      theory_id: 18031
    - title: Bean validation
      theory_id: 9355
    - title: Transaction management
      theory_id: 28141
    - title: Intro to H2 database
      theory_id: 27725
    - title: Relational databases with Spring Data
      theory_id: 18086
    - title: "SQL: structured query language"
      theory_id: 7054
    - title: Basic data types
      theory_id: 7123
    - title: Literals
      theory_id: 7400
    - title: Arithmetic expressions
      theory_id: 7409
    - title: Basic CREATE statement
      theory_id: 9084
    - title: Basic SELECT statement
      theory_id: 7392
    - title: SELECT FROM statement
      theory_id: 8611
    - title: Logic and comparison expressions
      theory_id: 8619
    - title: The NULL value
      theory_id: 7907
    - title: Special WHERE operators
      theory_id: 10521
    - title: Basic INSERT statement
      theory_id: 9059
    - title: Basic DELETE statement
      theory_id: 9075
    - title: Regexps in Java
      theory_id: 3670
    - title: "Regex sets, ranges, alternations"
      theory_id: 3674
    - title: Regex quantifiers
      theory_id: 3687
    - title: Regex shorthands
      theory_id: 3680
    - title: Regexes in programs
      theory_id: 3696
    - title: Intro to MySQL
      theory_id: 16662
    - title: Introduction to PostgreSQL
      theory_id: 17974
    - title: Introduction to transactions
      theory_id: 12144
    - title: Understanding Transactions
      theory_id: 12357
    - title: Generic methods
      theory_id: 3606
    - title: JPA relationships
      theory_id: 17787
    - title: Cascade operations
      theory_id: 27502
    - title: Embeddable and ElementCollection
      theory_id: 29504
    - title: Regular expression
      theory_id: 7580
    - title: Inner classes
      theory_id: 11505
  3:
    - title: LocalDate
      theory_id: 3592
    - title: LocalTime
      theory_id: 3593
    - title: LocalDateTime
      theory_id: 3617
    - title: Comparing dates and time
      theory_id: 3549
    - title: The utility class Collections
      theory_id: 3573
    - title: Many-to-many relationships
      theory_id: 28231
  4:
    - title: Introduction to Spring Testing
      theory_id: 27489
    - title: Setting up Spring Boot tests
      theory_id: 27507
    - title: Testing Beans
      theory_id: 29328
    - title: Logging in Spring Boot
      theory_id: 27485
    - title: Insecure Cryptographic Storage
      theory_id: 20069
    - title: Spring Security Crypto
      theory_id: 21866
    - title: "Web security, OWASP"
      theory_id: 14755
    - title: Getting started with Spring Security
      theory_id: 13856
    - title: Authentication
      theory_id: 31058
    - title: Authorization
      theory_id: 31611
    - title: Spring actuator
      theory_id: 27488
    - title: Property expressions
      theory_id: 28236
    - title: Custom User Store
      theory_id: 32430
    - title: Getting authenticated user details
      theory_id: 16710
    - title: Testing REST controllers
      theory_id: 34605
    - title: Testing Spring Security
      theory_id: 34892
    - title: HTTP Basic Auth
      theory_id: 7778
    - title: Unit testing with JUnit
      theory_id: 12640
    - title: Test lifecycle annotations
      theory_id: 12867
    - title: Parameterized test
      theory_id: 12877
    - title: Authentication and Authorization
      theory_id: 14219
    - title: RestTemplate
      theory_id: 25934
    - title: Encapsulating object creation
      theory_id: 3577
    - title: Factory method
      theory_id: 5761
    - title: Builder pattern
      theory_id: 16735
    - title: Builder
      theory_id: 5130
    - title: Abstract class
      theory_id: 3597
    - title: Abstract class vs interface
      theory_id: 3563
